version: "3"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./backend/app:/app
      - ./backend/assets:/assets
    environment:
      - BACKEND_CORS_ORIGINS=["http://localhost:3000","http://localhost:8000","http://localhost:8001"]

  frontend:
      build:
        context: ./frontend
        dockerfile: Dockerfile
      ports:
      - "3000:3000"
      volumes:
          - ./frontend:/frontend
      